apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nvjxiy3ob-nodejs 
  janus-idp.io/tekton: nvjxiy3ob-nodejs
  backstage.io/kubernetes-id: nvjxiy3ob-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nvjxiy3ob-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  