apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nvjxiy3ob-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nvjxiy3ob-nodejs 
  name: nvjxiy3ob-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nvjxiy3ob-nodejs 
